
start = input("Type 'Start'")
if start == "Start" or "start": 

		name = input("Make the name for your character.")
		print("//////////////////////////////////////")
		print("After a successful heist in Minas Tirith, you have gone to hide in the ruins of Osgiliath.")
		print("The prize was nothing more than King Aragorn\'s crown.")
		print("Upon the realization his prized crown was gone, he sent out a search party in order to find the heirloom, and punish the thief.")
		print("After a quick overlook of Pelennor Fields, you see the search party drawing closer.")
		print("What will you choose to do? Stay in Osgiliath and hide, flee to the Mountains of Shadow, or attempt to bribe the soldiers for your life?")
		print("Type 'Hide' for option one, 'Flee' for option two, and the 'Bribe' for option three.")
		choice = input("The time to decide is now.")
		if choice == "Hide":
			print ("You have chosen to hide within the city ruins.")
			print("////////////////////////////////////////")
			print ("The search party diligently roamed the decrepit capital, and after no luck of finding you they leave.")
			print ("After the soldiers do not return, you have some ideas as to where you could cash in your prize.")
			print("Two choices come to mind, either travel to the distant land of Harad, or try your luck with the enraged orcs.")
			print("Both suffered greatly during the war, and would love to take a stab at Gondor.")
			print("Now, do you wish to bargain with the orcs, or risk your life to get to Harad and bargain with their people?")
			print("Type 'Harad' to go to Harad, or type 'Orcs' to go to Cirith Ungol.")
			choicea = input("Where will you go for the gold?")
			if choicea == "Orcs": #This choice leads to Cirith Ungol
				print("The quest for Cirith Ungol has been decided.")
				print("////////////////////////////////////")
				print("You make your way to the edge of Mordor, which is surrounded by ominous mountains.")
				print("A large boulder begins to tumble down the mountain path you started to climb.")
				print("You press yourself against the side of the mountain to evade the massive rock, and manage to glimpse the person who threw the boulder.")
				print("The uruk addresses you, but you can not understand the rough dark language he speaks to you.")
				print("The language is black speech, a tongue that all of Sauron\'s followers speak.")
				print("Upon seeing the 30 shades of stupid on your face, he begins to speak in common tongue for you to understand.")
				print("He then spoke more clearly, saying 'I will tear off your arms you filthy shrakh if you don\'t tell me what you\'re doing in my mountain!'")
				print(" You then say to uruk 'Who do you think you are to threaten me so violently?'")
				print("The uruk responded as such, 'I am Khrash, Flesh Ripper they call me! I am the warchief of this land!'")
				print("'Be that as it may,' you retort, 'I am %s, the master thief, and I have come to bargain.'" %(name))
				print("Intrigued by your boldness, Khrash restrains you and leads to Cirith Ungol.")
				print("'What have you to offer us that we should trade with man-swine?' asked Khrash.")
				print("With an arrogant smirk, you reveal the crown to the horde of uruks.")
				print("'I will take nothing short of gold for such a prize!' you barter.")
				print("The uruks erupted in laughter.")
				print("'We have no gold fool! We have a poison dagger and a cloak of darkness. Choose one and we will trade,' said Khrash.")
				print("Type 'Poison' for the dagger, or 'Darkness' for the cloak.")
				choiceb = input("What piece of equipment will you choose?")
				if choiceb == "Darkness":  
					print("////////////////////////////////////")
					print("'Give me the cloak, and then I will give you the crown,' you negotiate.")
					print("Khrash gives you the stank eye.")
					print("In the end, you both decide to trade at the same time.")
					print("With the cloak, revenge upon the king will be easier.")
					print("In order to get to Minas Tirith, will you pass through Pelennor Fields, or go around the fields and try to enter the city from the side?")
					print("Type 'Fields' for Pelennor Fields, or 'Side' to travel around Pelennor Fields.")
					choicec = input("What course of action will you take?")
					if choicec == "Fields":
						print("///////////////////////////////")
						print("You travel through the fields and encounter an earth troll.")
						print("Its primordial language is impossible to decipher, but its intentions are clear.")
						print("The troll swung its mighty club in an attempt to flatten your feeble body.")
						print("You shout,'Parkour!' and jump onto its back and blind it with your cloak.")
						print("Blinded by the magical cloth, the troll trips and breaks its neck.")
						print("'Where there is a troll, there is a cave,' you think.")
						print("Eventually you stumble upon a cavern hidden by grass.")
						print("You venture into the cave, and it leads you into the dungeons of Minas Tirith.")
						print("Will you disguise yourself as a guard, or take the cannoli?")
						print("Type 'Disguise' for option one, and 'Cannoli' for option two.")
						choiced = input("How will you continue?")
						if choiced == "Disguise":
							print("//////////////////////////////")
							print("The guard did not see you approach; the magic cloak was doing its job.")
							print("It looked as if he used to be an adventurer, but sadly he was struck in the knee.")
							print("By using the guard's own sword, you run him through.")
							print("The armor fits snuggly, and the helmet manages to conceal your face.")
							print("You make your way out of the dungeons into the main armory.")
							print("The king can be seen making a venure up to his bedroom.")
							print("You follow.")
							print("How will you proceed?")
							print("Type 'Bret', 'Glass him', or 'Caesared'.")
							choicee = input("Choose one.")
							if choicee == "Bret":
								print("//////////////////////////////////")
								print("Taking inspiration from the great Bret Michaels, you poison the king by cutting his arm.")
								print("'Why have you done this to me!?' cried the king.")
								print("'Every rose has its thorn,' you say.")
								print("The end.")
							elif choicee == "Glass him":
								print("//////////////////////////////////")
								print("You shatter a glass cup over his face.")
								print("The end.")
							elif choicee == "Caesared":
								print("You stab the king 37 times in the chest.")
								print("The end.")
						elif choiced == "Cannoli":
							print("//////////////////////////////////")
							print("Leave the king, take the cannoli.")
							print("The end.")
						
					elif choicec == "Side":
						print("///////////////////////////////")
						print("You decide to travel around the fields and try to climp the side of the city's walls.")
						print("No one noticed your shadow-like body heave itself over the wall.")
						print("The magic cloak made you seem like an apparition.")
						print("Your new ability allows you to sneak into the King's chamber's.")
						print("You stab him.")
						print("The End.")
				elif choiceb == "Poison":
					print("//////////////////////////////////")
					print("Khrash trades you a poisonous dagger for the crown.")
					print("'Tis a fair trade,' said Khrash, 'now get out of my sight!'")
					print("You raise the dagger in triumph, and then bring it down into Khrash's abdomen.")
					print("In hindsight, killing an orc warchief in front of a horde of uruks was not he best idea.")
					print("Before you are dismembered, you steal a magic cloak from Khrash's corpse.")
					print("The cloak manages to conceal your body and you escape with two magical items.")
					print("All of the orcs are in a frenzy, and you barely got out of there alive.")
					print("Where to now?")
					print("Type 'Isengard' or 'Rohan'.")
					choicez = input("Where will you go?")
					if choicez == "Isengard":
						print("/////////////////////////////")
						print("The mighty Saruman probably would have some use for these magic items.")
						print("'The leader of the Wise will give me coin for these,' you say as you begin to travel to Isengard.")
						print("'Good thing I'm not a hobbit.'")
						print("People are always taking the Hobbits to Isengard.")
						print("You arrive at Orthanc and witness what appears to be an army of orcs.")
						print("Suddenly, Kratos and his son Atreus appeared.")
						print("'Stay behind me boi,' he said, 'we know nothing of this stranger.'")
						print("'Fear not, fellow travelers,' you say, 'I am here only to seek counsol with Saruman the White.'")
						print("Kratos looks at you with disdain.")
						print("'Only a fool would seek help from a god,' Kratos retorted with disapproval.")
						print("'Lettuce help him father,' pleaded Atreus.")
						print("'Okay boi, so we shall,' accepted Kratos.")
						print("With the combined power of boi, god, and player character, the army of orcs was defeated.")
						print("Will you help Kratos kill Saruman, or will you fight Kratos.")
						print("Type 'Kill' or 'Fight'.")
						choicex = input("Live or die. Make your choice.")
						if choicex == "Kill":
							print("///////////////////////////////////")
							print("'You will now need aid in fighting the wizard,' you say, 'for you are old and fatigued.'")
							print("Kratos replied with an annoyed look, and with one swing of his Leviathan axe the doors of Orthanc gave way.")
							print("Saruman greeted the travelers with an applause.")
							print("'Congradulations,' he taunted, 'you have made it to the boss battle.'")
							print("Atreus shot multiple arrows, but to no avail.")
							print("The wizard deflected the attack back toward Atreus, gravely wounding him.")
							print("This infuriated Kratos, which sent him into a Spartan rage.")
							print("Saruman did not stand a chance against the once god of war.")
							print("Kratos took hold of Saruman's head and ripped it off while yelling in anger.")
							print("The body of Atreus lays limp with arrows protruding from him.")
							print("A new fire began to blister Kratos's soul.")
							print("'The gods of this realm shall repay the debt of my son's blood with their own!")
							print("The Ghost of Sparta had been reborn.")
							print("You decide to aid Kratos in his new quest for vengeance.")
							print("After all of the gods are killed, you can take their stuff.")
							print("The end.")
						elif choicex == "Fight":
							print("/////////////////////////////////////")
							print("'I know of your purpose here, warrior, and I regret to inform that I must square up,' you threaten.")
							print("Kratos glares and reaches for his axe, in which you don't see him grab it because you are already running away.")
							print("It does not matter because he throws the axe into the back of your skull.")
							print("The end.")
					elif choicez == "Rohan":
						print("////////////////////////////////")
						print("You decide to journey toward the Lords of Horses.")
						print("The people of Rohan value their horses as much as their citizens.")
						print("Perhaps a trade can be made for one of their stallions.")
						print("On the journey there, you meet a caravan.")
						print("You hitch a ride all the way to Rohan, and thank the kind traveler.")
						print("It is about one mile to the city of Edoras.") 
						print("Out of no where, a great eagle swoops down and carries you to the city.")
						print("It drops you in the middle of the city.")
						print("From the main hall, you hear someone singing.")
						print("'I am the Globglogabgalab, the shwabble-dabble-wabble-gabble flibba blabba blab.'")
						print("The creature looked like a generic version of Jabba the Hut.")
						print("This is clearly not the place you need to be, so you turn around and walk away.")
						print("Will you turn around and murder the creature, or spare its life?")
						print("Type 'Murder' or 'Spare'.")
						choicey = input("What will you do?")
						if choicey == "Murder":
							print("//////////////////////////////////")
							print("You turn around and rip out the creature's intestines.")
							print("The end.")
						elif choicey == "Spare":
							print("//////////////////////////////////")
							print("You turn around and spare the creature from its life by stabbing it repeatedly.")
							print("The end.")
			elif choicea == "Harad":
				print("///////////////////////////////////////")
				print("You decide to venture into the desert land of Harad.")
				print("The scorched dunes ravaged your face as the grains of sand burned your skin.")
				print("A journey such as this has never been so arduous.")
				print("The quest for Harad lasted for a daunting five minutes.")
				print("By the time you make it to Harad, your body is completely dehydrated.")
				print("The Haradrim take you to their cleric.")
				print("As you lay collapsed, the healer uses a magic whetstone to hydrate your body.")
				print("You awaken in a dungeon.")
				
		elif choice == "Flee":
			print("///////////////////////////////////")
			print("You decide to make a run for it.")
			print("The nearby Mountains of Shadow could provide a refuge, because the Gondorian soldiers would not dare to enter there.")
			print("Sadly, the soldiers are on horseback, and they easily catch up to you.")
			print("'By orders of the King, you are under arrest on crimes of high treason!' ordered the chief guard.")
		elif choice == "Bribe":
			print("///////////////////////////////////")
			print("'Bribery is considered a federal offense, sir.'")
			print("*sounds of getting tased*")
		
		
		

